application: mfl-pipetechnology
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  max_pending_latency: 15.0s

default_expiration: "30d"

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  mime_type: image/x-icon

- url: /do
  login: admin
  script: wsgi.app

- url: /.*
  script: wsgi.app

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.po$
- ^(.*/)?.*\.posrc$
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.cmd$
- ^(.*/)?readme\.txt$
- ^(.*/)?run$
- ^(.*/)?makefile$
- ^(.*/)?Thumbs\.db$
#- ^django/(.*/)
